package org.mai.domain;

enum UartReceivedState {
    RECEIVE_COMMAND_SEND_SIZE_PID_DATA, RECEIVE_COMMAND_SEND_SIZE_SINUS_PID_DATA, RECEIVE_COMMAND_SEND_PID_DATA,
    RECEIVE_COMMAND_SEND_SINUS_PID_DATA, RECEIVED_COMMAND_END_TRANSMIT, RECEIVED_COMMAND_END_TRANSMIT_SINUS,
    RECEIVE_SIZE_ANGLE_POINT, RECEIVE_SIZE_ANGLE_SINUS_POINTS, RECEIVE_ANGLE_POINT,
    RECEIVED_COMMAND_SEND_SIZE_IMITATOR_DATA, RECEIVE_COMMAND_SEND_IMITATOR_DATA,
    RECEIVED_COMMAND_SEND_SIZE_IMITATOR_DATA_ADVANCE, RECEIVE_COMMAND_SEND_IMITATOR_DATA_ADVANCE,
    RECEIVE_ANGLE_SINUS_POINT
}
