package org.mai.domain;

enum UartTransmittedState {
    TRANSMIT_COMMAND, TRANSMIT_SIZE_PID_DATA, TRANSMIT_SIZE_SINUS_PID_DATA, TRANSMIT_PID_DATA,
    TRANSMIT_SINUS_PID_DATA, END_TRANSMIT_IMPULSE_DATA, TRANSMIT_SIZE_IMITATOR_DATA, TRANSMIT_IMITATOR_DATA,
    TRANSMIT_SIZE_IMITATOR_DATA_ADVANCE, TRANSMIT_IMITATOR_DATA_ADVANCE, END_TRANSMIT_SINUS
}
